### PR TITLE
Fix venera grave character not showing up

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/15532

20220103 141842 (osu!)

This required manual edits to the `otf` files to allow the bmfont export process to see the characters (which were previously "out of bound" according to it).

Not including the otf files as that would likely be an issue with licencing.

### CODE REVIEW

**Comment by bdach** [comment]
Weirdly enough the new assets look to be 10-15% smaller in size than the old ones, for some reason. And that goes not only for the raw `.png`s too, it's noticeable in the game as well - especially on the default skin, which makes it look a little bit janky:

| before | after |
| :-: | :-: |
| 2022-01-03-211210_743x121_scrot | 2022-01-03-211058_654x129_scrot |

I think the glyph measurements (as written to the `.bin` file) might have inadvertently changed somehow?

**Comment by peppy** [comment]
That's unfortunate, and would explain why the image sizes were a bit smaller. I'll have to go through the export process again.

Weirdly, I was using the saved settings that we always use from osu-framework...

**Comment by peppy** [comment]
Quite an ordeal, but things should be roughly correct now (within a pixel difference). Not really sure why this is happening, but I've accounted for the issue using visual comparison as it seems like less effort than figuring out why the metrics changed.

**Comment by bdach** [comment]
Sizing looks better, but there's still something wrong with baseline alignment:

2022-01-04-174737_772x129_scrot
2022-01-04-174746_776x90_scrot
2022-01-04-174756_148x73_scrot

All the texts are lower down than they should be.

**Comment by peppy** [comment]
RIP.

Guess I need to find another font editor, or fix this manually in the bin/png files.

**Comment by peppy** [comment]
I've updated this again using otf files provided by @bdach this time. All worked correctly, and I've compared to old fonts to confirm metrics have not changed this time around.

**Review by bdach — APPROVED** [review]
Looks correct to me :+1:

**Pull request merged**
