### PR TITLE
New sampleset for argon

### PR DESCRIPTION
**Pull request by nekodex**
My primary goal with this sampleset is to offer a fresh, modern take on stable/legacy's hitsounds that would work as a drop-in replacement for beatmaps that were created with stable/legacy's sampleset in mind. 

I've used reverb and increased stereo width to make the hitsounds less 'in your face' than the stable/legacy ones, making them more pleasant to the ear IMO. To compensate for potential audibility loss, I've used increased transients (punchyness), greater frequency range (with distortion/saturation/etc) and in some cases a volume bump to get them sounding equally legible.

I also decided to shorten the samples (relative to stable/legacy) in response to modern beatmaps being of increased difficulty/hitobject-density compared to maps from back when peppy created the stable/legacy sampleset.

In theory this allows for new players to progress further through harder maps before feeling the need to find an alternative skin/sampleset to hear what they're doing accurately - at which point, there's now conveniently also argon pro.

The sampleset does diverge a bit in some aspects (i.e. spinner sounds, fail sound, etc) to lean into lazer's aesthetic, but otherwise I hope the hitsounds should still be recognizable as some facsimile of their stable/legacy counterparts and hopefully still feel and play just as good (if not better) than stable/legacy did.

### CODE REVIEW

**Review by peppy — APPROVED** [review]

**Comment by Satorlous** [comment]
How to rollback this now? I really dont like new argon skin hitsounds, i'm user to the old ones...

**Comment by peppy** [comment]
You can use the triangles skin for the old ones.

**Comment by Satorlous** [comment]
@peppy Well, is there no way to use argon skin with old hitsounds?

**Comment by peppy** [comment]
Not for now.

**Comment by hachuyenden** [comment]
Is there a link so I can separately download these nekodex argon hitsounds into my skin? 😎

**Comment by hachuyenden** [comment]
> Is there a link so I can separately download these nekodex argon hitsounds into my skin? 😎
Oh, sorry, i find: https://github.com/ppy/osu-resources/tree/fd888233956290195477fc7879aa0d96a15236ce/osu.Game.Resources/Samples/Gameplay/Argon

**Pull request merged**
