### PR TITLE
Add skinnable mania resources

### PR DESCRIPTION
**Pull request by smoogipoo**

### CODE REVIEW

**Comment by peppy** [comment]
intentionally the non `@2x` versions? will mean that mania is running at half res in lazer

**Comment by smoogipoo** [comment]
Mania is split 50/50 on whether @2x versions exist :(

**Comment by peppy** [comment]
Some of the textures here look like @2x though, how is that handled?

**Comment by smoogipoo** [comment]
For the ones that did have `@2x` variants, I've included only those. For others I've included the non-`@2x`. Both lazer and stable fall back.

**Comment by peppy** [comment]
Oh, I see. I believe `@2x` in lazer is actually *insanely big* to the point that they are never used. Might be the reason the newer changes were only applied at 1x.

Have you confirmed that the `@2x` are even displayed in stable? We may want to just throw them away..

**Comment by peppy** [comment]
It's a pity the elements which *are* displayed larger are non-existant `@2x`, ie. the keys. The notes are just insanely big even at 1x...

**Comment by smoogipoo** [comment]
I haven't confirmed whether they're used in stable, no. Can do so, but probably tomorrow.

**Comment by peppy** [comment]
Any reason some 1x are prefered in this PR? ie. `mania-note1L-0@2x.png` exists in stable but the 1x version is committed here.

**Comment by smoogipoo** [comment]
Ah, I've just looked at stable's resources again and they differ from the default skin that I took from the forums. Stable's ones do indeed include all @2x. Will fix.

**Pull request merged**
