### PR TITLE
Add old intro assets

### PR DESCRIPTION
**Pull request by MiraiSubject**
This moves all the intro assets from `Samples/` to `Samples/Intro/{IntroType}` and adds the old intro assets.

A visualization of the resulting directory tree
```
Samples/Intro
 ┣ welcome
 ┃ ┣ seeya.mp3
 ┃ ┣ welcome.mp3
 ┃ ┗ welcome_piano.mp3
 ┗ lazer
 ┃ ┣ seeya.mp3
 ┃ ┗ welcome.mp3
```

### CODE REVIEW

**Comment by bdach** [comment]
Wasn't the "fallback" name suggested to be changed in the game-side PR? It'll be confusing if it does get changed there.

**Comment by MiraiSubject** [comment]
Oh yeah right, totally forgot about that. I did change it in the game side PR (just not pushed yet). I forgot to check this place. 

I will change it to `legacy` instead and update the game-side accordingly.

**Comment by peppy** [comment]
can you use `welcome` instead? i think i like intro sequences matching their song names.

**Comment by peppy** [comment]
You missed the other case. `lazer` -> `triangles`

**Comment by MiraiSubject** [comment]
>  i like intro sequences matching their song names.
> You missed the other case. `lazer` -> `triangles`

Totally missed the second part of your sentence. In that case wouldn't it be better then to call it `circles`, because `triangles` has its own `welcome` baked into the song? 

Both of the files in the currently-named `lazer` are used by the `circles` intro where `triangles` only uses `seeya` from it.

**Comment by peppy** [comment]
If they are shared put in the base folder. If they are specific put in a folder called the asme as the intro.

**Comment by peppy** [comment]
one welcome is upper case, the others aren't.

**Comment by peppy** [comment]
the @2x prefix is still there...

**Comment by MiraiSubject** [comment]
> the `@2x` prefix is still there...

Seems like I had a misunderstanding with the @2x suffix in https://github.com/ppy/osu/pull/9173#discussion_r439732189. I thought this meant that on a framework level just using `welcome-intro` would automatically just pick the correct asset.

I have renamed it here too.

**Pull request merged**
