### PR TITLE
All images should now have sRGB colorspace, matching the PNG profile

### PR DESCRIPTION
**Pull request by jai-sharma**
This should fix https://github.com/ppy/osu/issues/878

### CODE REVIEW

**Comment by peppy** [comment]
`Fonts` increased from 27.9mb to 46.6mb in your PR.

**Comment by jai-sharma** [comment]
Since every font .png file was grayscale before, the forced conversion to sRGB would mean that each pixel has gone from being represented by 8 bits to 32 bits which would contribute the size difference.

It might have been a bad idea to convert all the font images even though there weren't any issues regarding incorrectly rendered fonts. I'll revert the changes so they only apply to `Textures` and see if just that is enough to stop the errors.

**Comment by peppy** [comment]
I can seemingly fix the filesize without losing the sRGB profile

**Comment by peppy** [comment]
That's why you don't call your branches master when PRing

**Comment by peppy** [comment]
I'll squash and reopen the change on my own branch

**Comment by jai-sharma** [comment]
Ok

**Pull request merged**
