### PR TITLE
Add Triangles logo animation texture and shader

### PR DESCRIPTION
**Pull request by jorolf**
I'm a bit unsure if the texture should be that large considering that the mp4 was 10x smaller

### CODE REVIEW

**Comment by jorolf** [comment]
I might be able to create a better reference texture if I can get seperate videos of the "normal" animation and the "highlight". Preferably with a high framecount (I think RGB can save 1536 hue values)

**Comment by jorolf** [comment]
We might need to choose another "encoding"/format, the hue/jpg combo has some visible artifacts even at 90% compression

**Comment by peppy** [comment]
@jorolf can you attach the updated images in png24bit so i can experiment further and see what we need to make this work?

**Comment by jorolf** [comment]
This is the animation of just the "background":
background_better
And this is the animation of the "background" minus the "highlight":
highlight

**Comment by jorolf** [comment]
Also note that the original mp4 and the mp4 flyte provided are slightly different, the original cropped the black border.

**Comment by peppy** [comment]
image

Is the colour banding here the limit of 24bit colour? Doesn't seem like it. Also what's the red dot?

**Comment by jorolf** [comment]
The banding comes from the fact that I've only had 60 frames to work with and the red dot is probably some artifact in one of the earlier frames that overwrote the colour.

**Comment by peppy** [comment]
Can we interpolate between the frames (linear)?
Can we fix such artifacts (even if done manually)?

**Comment by jorolf** [comment]
I haven't tried to interpolate them because I couldn't think of a way how to (while generating the image). Some kind of blur might work though after the image has been generated. And yes these artifacts can be fixed manually with any (proper) image editor (Just keep the alpha and change the colour to the colour of the surrounding pixels)

**Comment by peppy** [comment]
How are you generating the image right now?

**Comment by jorolf** [comment]
I wrote this as an opengl program that layers the images by "blending". It loads each frame sequentially, draws it onto a framebuffer and saves it as a file at the end.

**Comment by peppy** [comment]
I guess ignoring the frame rate issues, the endpoints of the animation have missing lines, which looks pretty bad.

image

If this can be fixed we can probably get it in and work on improvements at a later date.

**Comment by peppy** [comment]
I've recompressed and fixed the red pixels:

logo-background

logo-highlight

I tried dropping transparency but it creates weird edge banding, so just left it be:

image

Please do advise on the gaps at the end.

**Comment by jorolf** [comment]
Those gaps could be related to floating point imprecision inside the shader. Either the hue is a bit off or the progress passed to the shader. Can you check if adding some epsilon value to `progress` helps?

**Comment by peppy** [comment]
I'm just going to leave the gaps for now. Fixes can be made in a follow-up PR by someone more perfectionist than I am (there several more small issues that can be fixed, like missing edges of curves due to incorrect pixel data).

**Pull request merged**
