### PR TITLE
Rename HoverSounds/HoverClickSounds samples

### PR DESCRIPTION
**Pull request by nekodex**

### CODE REVIEW

**Comment by nekodex** [comment]
Uh.. hold up, git auto rename detection made a mess of things

**Comment by peppy** [comment]
Not sure about reversing the naming structure here (`select-soft`/`select-softer` to `soft-select`/`softer-select`)

Any reasoning behind that? We generally would put variations like this at the end as is the case with namespacing stuff.

**Comment by nekodex** [comment]
The idea was so that component sounds would be sorted together, e.g. `tabselector-hover.wav`, `tabselector-select.wav`, `button-hover.wav`, `button-select.wav`, etc.

Also, I'm getting rid of 'soft', 'softer', etc in favour of more descriptive names (i.e. named after components/component-types), which can be seen in the follow-up pull requests...  which kinda makes them less 'variants' I guess.

**Comment by peppy** [comment]
Guess we'll see where it leads.

**Pull request merged**
