### PR TITLE
Update grade textures + Remove F grade texture

### LINKED ISSUE #57: Replace the rank icons with new ones
according to the new design available on the website

### PR DESCRIPTION
**Pull request by iiSaLMaN**
Closes #57 
Required for ppy/osu#4967

### CODE REVIEW

**Comment by iiSaLMaN** [comment]
Side note, F.png still exists but can be deleted after the migration of the 2 PRs, because osu! currently depends on the file

**Comment by peppy** [comment]
as i said twice already, your orer of dependency is wrong.

**Comment by iiSaLMaN** [comment]
fixed.

**Comment by peppy** [comment]
Remove the F.

**Comment by peppy** [comment]
Also please resize to match original sizing. And provide details on how you performed the render from SVG for reference.

**Comment by iiSaLMaN** [comment]
@peppy The original size of the SVG is 32x16, but that's too small so i resized to 256x128, almost the same as the original ones, i used Inkscape with `Export to PNG`

**Comment by peppy** [comment]
Eventually we'll want to implement these as drawables (with triangle animation) but this is fine for now.

**Pull request merged**
