### PR TITLE
Skins Legacy File Optimizetion

### PR DESCRIPTION
**Pull request by johnneijzen**
These File were compressed using FileOptimizer save around 2.7 MB it did take 1 hour 20 mins to compressed them

### CODE REVIEW

**Comment by peppy** [comment]
We intentionally do not do this due to increased decode times. feel free to do testing yourself to confirm (https://github.com/peppy/dotnet-benchmarks/tree/master/PngDecodeBenchmark)

**Comment by johnneijzen** [comment]
I see i did want to test using your benchmark but i get this error
System.DllNotFoundException: Unable to load DLL 'stbi' or one of its dependencies: The specified module could not be found. (0x8007007E) what i am doing wrong?

**Comment by peppy** [comment]
You would need to add the stbi nuget package. That repo only includes macOS libs at the moment.

**Comment by johnneijzen** [comment]
oh okay then i just try make small benchmark using stb_image.h to see how compression affect at C++ level before moving to C#. thanks you peppy anyway

**Pull request closed without merging**
