### PR TITLE
Add textures for mouse key overlays

### PR DESCRIPTION
**Pull request by Desconocidosmh**
These textures may be useful if we'll be implementing ppy/osu#5583

### CODE REVIEW

**Comment by Aergwyn** [comment]
Can't there be done something on osu!'s end to have different colours than adding them one by one here?

**Comment by Desconocidosmh** [comment]
I thought about it, but these textures seems to be a bit bluish, so it may do weird things to colors. It seems a bit weird, using one texture like this. Completely unchanged for one type of input, but changed for another. If we want to do it this way, perhaps all of these 3 textures should be black and white, so then we could apply any color to them on osu!'s end?

**Comment by Aergwyn** [comment]
That would be optimal, yes.

**Comment by peppy** [comment]
The new ones look very wrong (gray not white, and colour data missing from glow/shadow). Please wait for @arflyte to provide correct versions.

**Pull request closed without merging**
