### PR TITLE
Add inter font

### PR DESCRIPTION
**Pull request by gagahpangeran**
Add Inter font with regular, light, semi bold, and bold weight. Also italic version for each weight.

The configuration is from [bmfc file from framework](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Resources/Fonts/bmfont.bmfc) and add cyrillic and greek character. I also add the bmfc file for reference.

### CODE REVIEW

**Comment by bdach** [comment]
Think for 100% propriety we might also want to include [a copy of the license](https://www.fontsquirrel.com/license/inter) to adhere to its terms? It's something that [framework does](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Resources/Fonts/Roboto/LICENSE.txt), where applicable. Not sure.

**Comment by peppy** [comment]
Apart from the licence needing to be added, before we go ahead with this I think we should make sure the kerning pair count is not going to worsen our existing GC issues (ie. wait for an answer about gen2 object count having an adverse effect on gen0/1 performance).

None of the other fonts we use have such a large object/pair overhead - even Noto which has magnitudes more character specifications.

**Review by peppy — CHANGES_REQUESTED** [review]
Temporarily blocking

**Comment by peppy** [comment]
I've moved each font to their own folder and added local licencing information. Note that this will require further changes at the osu!-side due to the file location changes.

@smoogipoo if you find a chance please run your GC profiling against the osu-side branch with this font added and see if there's any discernible difference.

**Comment by smoogipoo** [comment]
image

Safe to say there's no difference.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
