### PR TITLE
Add new sprites for slider end / tick misses

### PR DESCRIPTION
**Pull request by peppy**
Pixelmator project file: [slider end miss tick.zip](https://github.com/ppy/osu-resources/files/13765030/slider.end.miss.tick.zip)

### CODE REVIEW

**Comment by bdach** [comment]
Not sure about the quality of these exports - this is what gimp shows me when I disable the alpha layer:

image
image

I'd expect the red/orange to extend to the bounds of the entire image and only be masked by alpha, rather than stop at the edges of the glow. Unlucky sampling could cause the outer parts of the glow to darken.

**Comment by peppy** [comment]
> I'd expect the red/orange to extend to the bounds of the entire image and only be masked by alpha, rather than stop at the edges of the glow.

I'm not sure how much this matters?

I'll fix the edge pixels though.

**Comment by bdach** [comment]
> I'm not sure how much this matters?

I mean I'm probably not too fussed, but given the debacle about proper exports for the mod extender thing a while back I figured you might?

**Comment by peppy** [comment]
As long as there's a glow the visibility of any incorrect RGB on alpha pixels is already negligible since it occurs on a transition of 0.01 to 0.00 alpha, so it's not a huge concern 👍.

Please re-check now, there edge pixels should at least be fixed.

**Comment by bdach** [comment]
Looks better now, yep:

image
image

**Review by bdach — APPROVED** [review]

**Pull request merged**
