### PR TITLE
Add welcome background

### PR DESCRIPTION
**Pull request by MiraiSubject**

### CODE REVIEW

**Comment by peppy** [comment]
I think I'd prefer this was in the `Intro/Welcome` folder just for organisation...

Also the png is over the top. Please use the attached jpeg instead (4x smaller and much faster to load).

menu-background-welcome

**Comment by vruss** [comment]
Will this background look alright if the game is running at 4K? The current triangle intro movie looks blurry at 4K.

**Comment by peppy** [comment]
It should look good enough, yes. It's already 98% blurred.

**Comment by MiraiSubject** [comment]
I've replaced it with the jpeg and placed it in `Intro/Welcome`. Game side code is also updated now with the new path

**Pull request merged**
