### PR TITLE
add supporter-required.png

### PR DESCRIPTION
**Pull request by JimmyC7834**
add osu.Game.Resources/Textures/Online/supporter-required.png for [this issue](https://github.com/ppy/osu/issues/13530)

image grabbed from https://osu.ppy.sh/beatmapsets

### CODE REVIEW

**Comment by bdach** [comment]
86e7e46 is not generally a valid or wanted commit and seems to indicate that you PR'd your change from a feature branch on your fork to your fork's `master`, and you now are PRing your `master` here to upstream `master`, which is incorrect. The feature branch from your fork is supposed to be PRed to `master`.

This was mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md) I had previously linked (see the "Make sure to submit pull requests off of a topic branch" section).

**Comment by gagahpangeran** [comment]
Another information, there are two resolution of this file in https://github.com/ppy/osu-web/tree/master/public/images/layout/beatmaps, `supporter-required.png` and `supporter-required@2x.png`.

Not sure which one best to use for osu.

**Comment by JimmyC7834** [comment]
I'm such an idiot, thanks for following up with me patiently.
So I would need to create a new pull request on my not-merged branch, right?

**Comment by bdach** [comment]
> Another information, there are two resolution of this file in https://github.com/ppy/osu-web/tree/master/public/images/layout/beatmaps, `supporter-required.png` and `supporter-required@2x.png`.
> 
> Not sure which one best to use for osu.

Good point. `Online/not-found.png` (the other sprite used for the beatmap listing overlay) seems to be of the `@2x` size (compare: [web `@2x`](https://github.com/ppy/osu-web/blob/master/public/images/layout/beatmaps/not-found%402x.png), [resources sprite](https://github.com/ppy/osu-resources/blob/master/osu.Game.Resources/Textures/Online/not-found.png)). So it should probably be `@2x` here too.

> So I would need to create a new pull request on my not-merged branch, right?

Correct, I don't believe it is possible to change the source branch of an opened pull. You're best off closing this one and opening another, with the correct asset this time.

**Comment by JimmyC7834** [comment]
Thanks for the guide

**Pull request closed without merging**
