### PR TITLE
Adjust shader to support masking SSBO

### PR DESCRIPTION
**Pull request by smoogipoo**
@peppy please test that osu runs with this before merging, as I'm unsure about the other shaders.

### CODE REVIEW

**Comment by peppy** [comment]
Are you mostly interested in macOS, or should I also test windows?

**Comment by smoogipoo** [comment]
Both would be good, but metal is the one likely to fail.

**Comment by peppy** [comment]
Seems fine on metal.

**Comment by smoogipoo** [comment]
Works fine on d3d for me.

**Review by peppy — APPROVED** [review]

**Pull request merged**
