### PR TITLE
Fix icon render script not negating correctly on newer imagemagick versions

### PR DESCRIPTION
**Pull request by bdach**
See conversation at https://discord.com/channels/188630481301012481/188630652340404224/1225325831988052039.

### CODE REVIEW

**Comment by peppy** [comment]
Seems better but also inverse of other icons:

2024-04-04 14 48 48@2x
2024-04-04 14 49 00@2x

**Comment by bdach** [comment]
That's... not what it does on my machine. Even using imagemagick 7.1.1. So I'm very confused.

Dunno what to do with this at this stage. Are you sure the source svgs are black still? Maybe you've edited them?

**Comment by peppy** [comment]
I don't believe I've changed the sources:

turtle
rabbit


But again, keep in mind these were provided by a different designer and not figma exports. So they may not match our standard expectations.

**Comment by bdach** [comment]
The script presumes the assets to be in black:

https://github.com/ppy/osu-resources/blob/d7ea79d7d8d15c6d1dc8eb1047e9193c9212744c/osu.Game.Resources/Textures/Icons/render.sh#L13-L14

and the linked svgs are white. So I guess this would be expected behaviour.

**Comment by peppy** [comment]
Yeah, make sense.

Safe to say the new script is more correct than the old on my PC anyways.

**Review by peppy — APPROVED** [review]

**Pull request merged**
