### PR TITLE
Update samples for `ButtonSystem`/`MainMenu`

### PR DESCRIPTION
**Pull request by nekodex**
- Adds new versions of `Menu/osu-logo-select`, `Menu/button-play-select` and `Menu/button-default-select` (replacing `Menu/button-{solo,generic,edit,direct}-select` which were duplicates)
- Adds new tiered 'back' samples: `Menu/back-to-logo`, `Menu/back-to-top`, `UI/screen-back`
- Adds some 'swoosh' samples to match `MainMenu` animations: `Menu/osu-logo-swoosh`, `Menu/reappear-swoosh` (separate from 'back' samples for future flexibility)
- Removes `now-playing-pop-in` and `now-playing-pop-out` (usages replaced by `overlay-pop-in`, `overlay-pop-out`)

### CODE REVIEW

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
Sounding really solid now 👍

**Comment by Mineplayerminer** [comment]
Is there a way to bring back the old sounds?

**Comment by peppy** [comment]
> Is there a way to bring back the old sounds?

There isn't. We might add this in the future.

**Comment by Mineplayerminer** [comment]
> > Is there a way to bring back the old sounds?
> 
> There isn't. We might add this in the future.

That would be cool! Also, why not make the whole game menu UI customizable like changing the colors of some elements? I know these may not be that necessary or important, but they would be still nice to have.

**Pull request merged**
