### PR TITLE
Update backgrounds

### PR DESCRIPTION
**Pull request by arflyte**
Brand new wallpapers.

### CODE REVIEW

**Comment by bdach** [comment]
Not sure it's good that the logo outline is on the new ones. Probably needs double-checking that it doesn't double up on some screens (something like player loader is most likely to look bad I'd say).

**Comment by peppy** [comment]
Might be best to just remove the logo? It was never supposed to be there for the client backgrounds.

**Comment by Stoppedpuma** [comment]
clipboard

Are these white tips on `menu-background-4` intentional?

**Comment by peppy** [comment]
I don't find these looking good in the game. Even without compressing, they look jpeg noisy.

**Comment by arflyte** [comment]
Hmm, didn't have much time to simmer it. I'll look into it again, and probably make it a lot less noisy. Had some ideas.

**Review by peppy — APPROVED** [review]

**Pull request merged**
